language: python
jobs:
  include:
  - name: Python 3.7.1 on Xenial Linux
    python: 3.7
  - name: Python 3.7.2 on macOS
    os: osx
    osx_image: xcode11
    language: shell
    before_install: python3 --version ; pip3 --version ; sw_vers
  - name: Python 3.7.4 on Windows
    os: windows
    language: shell
    before_install:
    - choco install python --version 3.7
    - python -m pip install --upgrade pip
    - pip3 install windows-curses==2.1.0
    env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
install:
- pip3 install -r requirements.txt
- pip3 install -e .
- pip3 install -r requirements-dev.txt
- pip3 freeze --local
script:
- black --check .
- pytest -vv -s
deploy:
  provider: pypi
  user: biznetgio
  password:
    secure: GRsVWTvvqxQBhV65KiVdW75mfhUzfSydnwPxd0npYGofCKL4eO6wumAnZ1w/cywrk2wJdVzuqgfZAjTnrXLXOzZqKKjuVlvT0P4Oq8JOInAlY5ESP2z9GxczigK6s6bPEU8N3t+vV2tZJoa/hOFWnDU/Esbnrrddc8P9DefOqkM+EX/5xURJp/ngPErrI1Y0SiJGcp9rINljc2ZrUQ5BDrAzmkDKCLapewBZTmvEC8g0psBGRuRUFwHyh3S93W7FWjhAXosknfipOxIsr9zhscLUliKsP1zQ+ylUNQvDlQ+0eJTO86kZeWzcOqItVjUZwyubuMgUcWOCsbPH/bTFDJ9Niz0SsPPtbBEvt8zsmc6M+kZRbut6Epo70UJxiZV4c8+EJhIHoaGbaDjgmMgT+HCSX2M1XgmdYlamFHNHhOZcYQsYMPjvBguiEHaP+a6K/PzAewnOJYzlUpqEIJuDjCzAB54tlELKk3RNbixQ5UzheiPOfT8Jn0HLZvzPaR0faOhBYoXQ8M4Sfj/jmO/iJrLrawg4vH6BhmO61Zxw3ntW9oEtMI0+YIkmyk2HP8r23bqBBbvV0KGYo+beaolYRzQ96v4z/C1bPJS0QyGlZqmiahceeOqV322JEwHU89tjHR35NIesHrtEdnTsUHZptMirINWW59W6f8H/g2HZlzo=
  on:
    tags: true
