language: python
python:
    - '3.6'
install:
    - pip install -r requirements.txt
    - pip install -e .
    - pip install -r requirements-dev.txt
    - pip freeze --local
script:
    - black --check .
    - pytest -vv -s
