language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -e .
  - pip install -e .[extra]
  - python setup.py test
# command to run tests
script:
  - pytest # or py.test for Python versions 3.5 and below
