language: python
python:
- '3.6'
install:
- pip install -e .
- pip install coverage pytest pytest-cov
- python setup.py test
script:
- pytest
before_install:
- openssl aes-256-cbc -K $encrypted_214af5c02543_key -iv $encrypted_214af5c02543_iv
  -in tests/.test.env.enc -out tests/.test.env -d
- mv tests/.test.env $HOME/.neo.env
deploy:
  provider: pypi
  user: Your username
  password:
    secure: XPwXuf4BAPsVI9y/0wNnvRWv4peAYsfctXxmNlBs5ykSp74dgLSoPeI0ySiMIAYvJ7Bx3ZjXy5/kfzQgckDVP8T62oH7+maGCtm9p2la0sYNtEdpZS8zW74fHjf1fvJcm3SxbvbUC2VGn/uVJAbuRhhvA8NmwqukdL6B41E3InqOETcyjiVURkHIRehs3NRdbdKXLVb8cmFsRhGqY/EGQGLKQ2Aeo5C9rzh4t/WXa8s74ehY8aUmJok4Xlxz+YHNd+pDHmfRb0IU1sz8h1T5amOMoskW4AN+Lp2xQI/aetatk2HB3r1X7uIyLt6UgeXj4WedG8U7xp26DYCV9T1XerQUutfg5wywNGfFnaRJAfkTNEeFotXCYyJ9SjnjulUlHFpwCxcTx4k6l/usBVIQuoOpWKaFXFXJF5uN2oueimyISyttiJ2+6jtofpWBsySeqAfc9R6Jp/1hqqwFtN5LoG4kpb6hdCbgEuBKCnIsKK/uSFtcX86QQRp3nvoWrJa7R3L2NWSvEOcM1o5IgZ2ok+kBRw0nFpslYnto2IE4r38DHXMOY3sOPavEWlVOFliCfP8Ib9/kPcbxF4u93Yx0DS35sr25QCcAMN3aAVRKvSsmlHTRSMvnCmMzqB3wXto4i5ruIx0VJpuy3ZaKrojZWACT+3Ur7nAdawlrcGZaSGY=
  on:
    tags: true
  skip_cleanup: true
